CREATE TABLE "submissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"submitter_name" text NOT NULL,
	"submitter_email" text NOT NULL,
	"submitter_role" text NOT NULL,
	"discord_username" text NOT NULL,
	"telegram_username" text NOT NULL,
	"founder_name" text NOT NULL,
	"founder_twitter" text NOT NULL,
	"team_members" jsonb DEFAULT '[]'::jsonb,
	"project_name" text NOT NULL,
	"project_summary" text NOT NULL,
	"arcium_role" text NOT NULL,
	"logo_url" text NOT NULL,
	"category" text NOT NULL,
	"website" text NOT NULL,
	"project_twitter" text NOT NULL,
	"project_email" text NOT NULL,
	"discord_invite" text,
	"telegram_invite" text,
	"additional_context" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
